version: "3.3"
services:
    client-card-app:
        image: clojure:lein
        container_name: cliet-card-app
        volumes:
            - .:/home/app
        working_dir: /home/app
        entrypoint: 'lein repl :headless :host 0.0.0.0 :port 7888'
        environment:
            PORT: 3000
            DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres'
        ports:
            - "7888:7888"
            - "3000:3000"

    client-card-db:
        image: postgres
        container_name: cliet-card-db
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    client-card-db-test:
        image: postgres
        container_name: cliet-card-db-test
        environment:
            POSTGRES_PASSWORD: postgresql
            POSTGRES_USER: postgres
        volumes:
            - ./pgdatatest:/var/lib/postgresql/data
        ports:
            - "5433:5432"