version: "3.3"
services:
  postgres:
    image: postgres
    container_name: cliet-card-db
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"